# -*- coding: utf-8 -*-
"""Hosuing Prices.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KF9BbOU9ZKrSNpvad-aVo4LUmKhsJBSx
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

data = pd.read_csv('housing.csv')
y = data['households']#  y
x = data['population'] # x
x = x.values.reshape(-1,1)
y=y.values

plt.figure(figsize =(8,6))

plt.scatter(x,y)
reg = LinearRegression()
reg.fit(x,y)

train_x, test_x, train_y, test_y = train_test_split(x,y, test_size=0.33, random_state = 1)

reg.fit(train_x, train_y)
y_pred = reg.predict(train_x)
plt.scatter(train_x, train_y)

plt.plot(x, reg.predict(x), color='red', linewidth=2, label='Line of Best Fit')


plt.title('Population vs Households')
plt.xlabel('Population')
plt.ylabel('Households')
plt.legend()
plt.grid(True)



